// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Gartentraum Odenwald",
    "city": "Bad König",
    "foundedYear": "",
    "teamSize": "Familienbetrieb, 3 Köpfe",
    "machines": ""
  },
  "claim": "Gartenbau im Odenwald",
  "heroSubline": "Michael und Benjamin Arnold aus Bad König. Planung, Pflaster, Terrasse, Naturstein und Pflege im festen Team. Einsatzgebiet: Odenwald und rund 40 km um Bad König.",
  "services": [
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom leeren Grundstück oder verwilderten Garten zur fertigen Anlage: Planung, Erdarbeiten, Steinarbeiten, Wege, Beete, Rasen.",
      "intro": "Eine Gartenneugestaltung ist bei uns selten nur Bepflanzung. Meist kommen Rückbau, Erdmodellierung, Entwässerung, Sitzmauern, Wege und Terrasse dazu. Wir planen das in einem Zug und führen es mit einem festen Dreier-Team aus, damit die Gewerke aufeinander passen.",
      "bullets": [
        "Aufmaß vor Ort, Bestandsaufnahme von Boden, Gefälle und Zugang",
        "Planung mit klaren Varianten, nicht mit einer einzigen Idee",
        "Erdarbeiten, Rückbau und Entsorgung des Aushubs im eigenen Ablauf",
        "Wege, Terrasse, Sitzmauern, Beete und Rasen aus einer Hand",
        "Referenzen im Odenwald zeigen wir auf Wunsch vor Ort"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zugang, Boden und Gefälle und klären, was baulich sinnvoll ist."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten und Terrasse meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Bad König | Gartentraum Odenwald",
        "description": "Gartenneugestaltung mit Planung, Erdarbeiten, Wegen und Bepflanzung. Aufmaß vor Ort, klare Positionen, feste Bauzeit."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Garagenzufahrt, Wege und Hofflächen mit tragfähigem Unterbau und sauberer Entwässerung.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, planen das Gefälle mit und lösen die Entwässerung, bevor der erste Stein liegt. Garageneinfahrten und Eingangsbereiche sind bei uns Alltag.",
      "bullets": [
        "Einfahrt, Zufahrt, Wege, Hof und Terrassenflächen",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Entwässerung, Rinnen und Anschluss an Bestandsflächen",
        "Randeinfassungen, Muster, Naturstein und Betonstein",
        "Referenzflächen in der Umgebung auf Wunsch zeigen wir gern"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Bad König | Gartentraum Odenwald",
        "description": "Pflasterarbeiten für Einfahrt, Wege und Hofflächen: tragfähiger Unterbau, geplante Entwässerung, saubere Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus Naturstein, Keramik oder Holz, inklusive Unterbau, Sichtschutz und Beleuchtung.",
      "intro": "Die Terrasse ist der Teil des Gartens, der täglich benutzt wird. Materialwahl, Untergrund und Entwässerung entscheiden darüber, wie sie nach fünf Jahren aussieht, nicht das Muster im Prospekt. Vergrößerungen bestehender Terrassen und Anschlüsse an vorhandene Platten sind bei uns Standard.",
      "bullets": [
        "Materialien: Keramik, Naturstein, Betonplatten, Holz und WPC",
        "Unterbau: Splittbett, Stelzlager oder Punktfundamente",
        "Sichtschutz, Pergola und Übergang zum Rasen mitgeplant",
        "Beleuchtung und Stromleitungen vor dem Belag verlegt",
        "Pflegehinweise je nach Material bei der Übergabe"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Holz oder Keramik?",
          "a": "Holz ist warm und lebendig, braucht aber Pflege. Keramik und Naturstein sind pflegeleicht und farbstabil. Wir zeigen beides an realen Flächen, bevor Sie sich festlegen."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Bad König | Gartentraum Odenwald",
        "description": "Terrassenbau mit Naturstein, Keramik oder Holz: geplanter Unterbau, Entwässerung, Sichtschutz und Beleuchtung."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmalige Pflege oder Pflegevertrag: Rasen, Hecken, Beete, Steinflächen und Saisonarbeiten.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn der Garten aus dem Ruder gelaufen ist, und den Pflegevertrag über die Saison, gern auch für Anlagen, die wir selbst gebaut haben.",
      "bullets": [
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Heckenschnitt, Formschnitt und Rückschnitt von Sträuchern",
        "Laub, Winterdienst und Frühjahrsputz auf Wunsch"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Bad König | Gartentraum Odenwald",
        "description": "Gartenpflege als Einmalpflege oder Pflegevertrag: Rasen, Heckenschnitt, Beete und Saisonarbeiten mit festen Terminen."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Zäune, Sichtschutzwände und Gabionen, kalkuliert nach laufenden Metern.",
      "intro": "Zaun und Sichtschutz werden nach laufenden Metern gerechnet. Entscheidend sind Höhe, Fundament und Grenzverlauf. Wir sagen vorab, wo eine Genehmigung oder eine Abstimmung mit dem Nachbarn nötig ist.",
      "bullets": [
        "Doppelstabmatten, Holz, WPC, Aluminium und Gabionen",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Hinweise zu Grenzbebauung, Höhe und örtlichen Satzungen",
        "Tore und Türen mit passender Beschlagtechnik",
        "Beispiele aus der Region auf Wunsch vor Ort"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun & Sichtschutz in Bad König | Gartentraum Odenwald",
        "description": "Zaun und Sichtschutz nach laufenden Metern: Doppelstabmatten, Holz, Gabionen, mit Fundament und Hinweisen zur Genehmigung."
      }
    },
    {
      "key": "bewaesserung",
      "slug": "bewaesserung",
      "label": "Bewässerung",
      "navLabel": "Bewässerung",
      "cta": "Bewässerung prüfen",
      "unit": "qm",
      "teaser": "Automatische Bewässerung für Rasen und Beete, inklusive Steuerung und Wartung.",
      "intro": "Eine automatische Bewässerung spart Wasser, weil sie früh morgens und nach Bedarf läuft. Wichtig ist die Auslegung: Druck, Durchfluss und Kreise müssen zusammenpassen, sonst wird die Fläche ungleich versorgt.",
      "bullets": [
        "Planung nach Druck, Durchfluss und Flächenzuschnitt",
        "Getrennte Kreise für Rasen, Beete und Tropfbewässerung",
        "Steuerung mit Regensensor oder App-Anbindung",
        "Nachrüstung in bestehende Gärten mit minimalem Aufgraben",
        "Wartung: Frühjahrsinbetriebnahme und Einwintern"
      ],
      "ablauf": [
        {
          "title": "Fläche & Wasser",
          "text": "Wir brauchen Flächengröße sowie Druck und Durchfluss am Hausanschluss."
        },
        {
          "title": "Auslegung",
          "text": "Kreise, Regner und Tropflinien werden auf die Fläche gerechnet."
        },
        {
          "title": "Angebot",
          "text": "Material, Verlegung und Steuerung transparent aufgeschlüsselt."
        },
        {
          "title": "Einbau",
          "text": "Verlegen, Einregulieren, Programmierung und Einweisung."
        }
      ],
      "faq": [
        {
          "q": "Muss der Rasen dafür raus?",
          "a": "Nein. Wir verlegen mit einem Verlegepflug, die Schnitte wachsen in der Regel innerhalb weniger Wochen zu."
        },
        {
          "q": "Was kostet die Wartung?",
          "a": "Inbetriebnahme und Einwintern sind planbare Pauschalen, die wir mit dem Angebot ausweisen."
        }
      ],
      "image": "/assets/leistungen/bewaesserung-rasen-und-beete.webp",
      "estimate": {
        "minPerUnit": 12,
        "maxPerUnit": 35,
        "baseMin": 1800
      },
      "seo": {
        "title": "Bewässerung in Bad König | Gartentraum Odenwald",
        "description": "Automatische Bewässerung für Rasen und Beete: Planung nach Druck und Durchfluss, Steuerung, Nachrüstung und Wartung."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Bad König",
    "radiusKm": 40,
    "note": "Wir arbeiten im Odenwald und rund 40 km um Bad König. Außerhalb schauen wir uns Anfragen ab einer bestimmten Projektgröße im Einzelfall an.",
    "plzPrefixes": [
      "64"
    ],
    "borderPlzPrefixes": [
      "63",
      "69",
      "74"
    ],
    "places": [
      "Bad König",
      "Michelstadt",
      "Erbach",
      "Höchst im Odenwald",
      "Breuberg",
      "Lützelbach",
      "Brensbach",
      "Fränkisch-Crumbach",
      "Reichelsheim",
      "Groß-Umstadt",
      "Amorbach",
      "Miltenberg"
    ],
    "center": {
      "lat": 49.75983,
      "lng": 9.00149
    }
  },
  "contact": {
    "phone": "01525 5774532",
    "phoneLink": "tel:+4915255774532",
    "whatsapp": "01525 5774532",
    "whatsappLink": "https://wa.me/4915255774532",
    "whatsappPrefill": "Hallo Gartentraum Odenwald, ich habe eine Frage zu einem Gartenprojekt im Odenwald, konkret in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Helfer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir sind ein kleiner Familienbetrieb im Odenwald und suchen Verstärkung für unsere Baustellen rund um Bad König. Erzählen Sie uns kurz, was Sie können, den Rest klären wir am Telefon oder bei einem Kaffee im Büro.",
    "roles": [
      "Landschaftsgärtner/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in mit handwerklicher Erfahrung",
      "Auszubildende/r Landschaftsgärtner/in"
    ],
    "benefits": [
      "Kleines festes Team, kein Wechsel von Kolonne zu Kolonne",
      "Baustellen im Odenwald, kurze Wege statt langer Autobahnfahrten",
      "Pünktliche Bezahlung, geregelte Arbeitszeiten, Winter geplant",
      "Einarbeitung in Pflaster, Naturstein und Terrassenbau"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Familienbetrieb",
        "text": "Michael und Benjamin Arnold sind bei jedem Projekt persönlich dabei, nicht nur am Anfang."
      },
      {
        "label": "Aufmaß vor Ort",
        "text": "Verbindliche Preise nennen wir erst, wenn wir Fläche, Boden und Zugang gesehen haben."
      },
      {
        "label": "Feste Bauzeit",
        "text": "Termine und Änderungen werden vor Baubeginn schriftlich festgehalten."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
