// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.5,
  "totalRatings": 8,
  "reviews": [
    {
      "author": "Tina Richter",
      "rating": 5,
      "text": "Gartenarbeiten und Bodenplatte für Gärateschuppen und Liegeplätze. Danke an Michael und Benjamin, für die Arbeiten bei uns im Garten. Sehr freundlich und bei uns immer wieder gern gesehen, freuen uns schon auf unser nächstes gemeinsames Projekt, Gartenmauer ! Auf einen Kaffee dürft ihr jederzeit vorbei schauen. Liebe Grüße Tina Richter.",
      "time": "vor 4 Jahren"
    },
    {
      "author": "Angelika Bierhenkel",
      "rating": 5,
      "text": "Vielen Dank an das Team von Gartentraum Odenwald!\nUnsere Terrasse wurde vergrößert und neue Platten verlegt. Wir wurden sehr gut beraten und uns wurden verschiedene Möglichkeiten unterbreitet! Herr Arnold arbeitet äußerst zuverlässig, präzise und zügig. Innerhalb weniger Tage wurde unsere Terrasse komplett neu gemacht. Der Sommer kann kommen! Wir sind sehr zufrieden und bedanken uns.\n\nFamilie Bierhenkel",
      "time": "vor 2 Jahren"
    },
    {
      "author": "Klaus S",
      "rating": 5,
      "text": "Im Jahr 2021 wurde bei uns der Garten komplett saniert und wieder in eine Wohlfühl-Oase verwandelt. Wir waren super zufrieden und haben für 2022 die Garageneinfahrt, sowie den Eingangsbereich neu gestaltet. Auch dieses wurde super umgesetzt. Das Team war super freundlich, hat uns top beraten. Alles wurde so umgesetzt wie vereinbart in professioneller Qualität.\nEs war uns eine Freude und ich kann die Truppe uneingeschränkt weiter empfehlen.\nVielen Dank an Michael & Benjamin",
      "time": "vor 4 Jahren"
    },
    {
      "author": "Sven Fuchs",
      "rating": 5,
      "text": "Bin mehr als zufrieden mit der Arbeit, den Ideen und der Umsetzung des Teams von Gartentraum Odenwald 👍👍\nAlle sind super sympathische Typen mit denen man auch gerne mal ein spässchen machen kann, die Arbeit dennoch stets gewissenhaft und mit äußerster Präzision ausgeführt wird :)\n\nBeste Grüße",
      "time": "vor 3 Jahren"
    }
  ]
};
